Repository OMRI-Tech/FE-omri-app, pull requests merged in 2022-06, with the labels that each got.

#17 feat: Add MenuLayout for Main view app
  package.json
  src/assets/fonts/Poppins.ttf
  src/assets/icons/heart.svg
  src/assets/icons/out_calendar.svg
  src/assets/icons/out_profile.svg
  src/assets/icons/out_ranking.svg
  src/assets/icons/triangle.svg
  src/assets/icons/trophy.svg
  src/css/menu.sass
  src/layouts/MenuLayout.vue
  src/pages/Menu.vue
  src/router/routes.js
Labels: historia

#20 disenio register
  src/pages/Register.vue
  src/router/routes.js
Labels: historia

#24 contenedor ajustado
  src/pages/Register.vue
Labels: bug

#33 Fix styles in main rectangle and linear progress
  src/css/menu.sass
  src/pages/Menu.vue
Labels: bug

#34 Quasar improvements
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  package.json
  public/.htaccess
  quasar.conf.js
  src/boot/axios.js
  src/css/app.sass
  src/css/app.scss
  src/index.template.html
  src/router/index.js
  src/router/routes.js
  src/store/auth/actions.js
  src/store/auth/getters.js
  src/store/auth/index.js
  src/store/auth/mutations.js
  src/store/auth/state.js
  src/store/index.js
  src/store/store-flag.d.ts
  yarn.lock
Labels: enhancement

#37 sin q-card y sin styles en template
  src/pages/Register.vue
Labels: bug

#38 Lesson Screen
  src/css/app.sass
  src/css/fonts/Poppins/OFL.txt
  src/css/fonts/Poppins/Poppins-Black.ttf
  src/css/fonts/Poppins/Poppins-BlackItalic.ttf
  src/css/fonts/Poppins/Poppins-Bold.ttf
  src/css/fonts/Poppins/Poppins-BoldItalic.ttf
  src/css/fonts/Poppins/Poppins-ExtraBold.ttf
  src/css/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
  src/css/fonts/Poppins/Poppins-ExtraLight.ttf
  src/css/fonts/Poppins/Poppins-ExtraLightItalic.ttf
  src/css/fonts/Poppins/Poppins-Italic.ttf
  src/css/fonts/Poppins/Poppins-Light.ttf
  src/css/fonts/Poppins/Poppins-LightItalic.ttf
  src/css/fonts/Poppins/Poppins-Medium.ttf
  src/css/fonts/Poppins/Poppins-MediumItalic.ttf
  src/css/fonts/Poppins/Poppins-Regular.ttf
  src/css/fonts/Poppins/Poppins-SemiBold.ttf
  src/css/fonts/Poppins/Poppins-SemiBoldItalic.ttf
  src/css/fonts/Poppins/Poppins-Thin.ttf
  src/css/fonts/Poppins/Poppins-ThinItalic.ttf
  src/layouts/LessonLayout.vue
  src/pages/LessonEmpty.vue
  src/router/routes.js
  yarn.lock
Labels: historia
